name: Deployment
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: texlive/texlive:latest-small
    steps:
      - uses: actions/checkout@v6
      - run: sh -e scripts/install-dependencies.sh
      - run: make all
      - uses: softprops/action-gh-release@v3
        with:
          files: dist/*.pdf
